refactor: Simplify Dockerfile RUN commands
href: https://github.com/hadolint/hadolint

diff --git a/base/single/Dockerfile b/base/single/Dockerfile
--- a/base/single/Dockerfile
+++ b/base/single/Dockerfile
@@ -3,6 +3,9 @@ FROM debian:10-slim
 ARG OPAM_VERSION
 ENV OPAM_VERSION=${OPAM_VERSION}
 
+SHELL ["/bin/bash", "--login", "-o", "pipefail", "-c"]
+
+# hadolint ignore=DL3008
 RUN cat /proc/cpuinfo /proc/meminfo; apt-get update -y -q \
   && DEBIAN_FRONTEND=noninteractive apt-get install -y -q --no-install-recommends \
     autoconf \
@@ -25,15 +28,14 @@ RUN cat /proc/cpuinfo /proc/meminfo; apt-get update -y -q \
     unzip \
   && [ -n "${OPAM_VERSION}" ] \
   && binary="opam-${OPAM_VERSION}-$(uname -m)-$(uname -s | tr '[:upper:]' '[:lower:]')" \
-  && cd /tmp \
-  && curl -fSOL https://github.com/ocaml/opam/releases/download/${OPAM_VERSION}/${binary} \
-  && curl -fSOL https://github.com/ocaml/opam/releases/download/${OPAM_VERSION}/${binary}.asc \
+  && curl -fSL -o "/tmp/${binary}" "https://github.com/ocaml/opam/releases/download/${OPAM_VERSION}/${binary}" \
+  && curl -fSL -o "/tmp/${binary}.asc" "https://github.com/ocaml/opam/releases/download/${OPAM_VERSION}/${binary}.asc" \
   && curl -fsSL https://keybase.io/altgr/pgp_keys.asc | gpg --batch --import \
-  && gpg --batch --verify ${binary}.asc ${binary} \
+  && gpg --batch --verify "/tmp/${binary}.asc" "/tmp/${binary}" \
   && set -x \
-  && mv ${binary} /usr/local/bin/opam \
+  && mv "/tmp/${binary}" /usr/local/bin/opam \
   && chmod a+x /usr/local/bin/opam \
-  && rm -f ${binary}.asc \
+  && rm -f "/tmp/${binary}.asc" \
   && rm -fr /root/.gnupg \
   && DEBIAN_FRONTEND=noninteractive apt-get purge -y -q --auto-remove gnupg \
   && apt-get clean \
@@ -69,7 +71,8 @@ ENV DUNE_VERSION=${DUNE_VERSION}
 ARG NUM_VERSION=0
 # or 1.3
 
-RUN ["/bin/bash", "--login", "-c", "set -x \
+# hadolint ignore=SC2046
+RUN set -x \
   && opam init --auto-setup --yes --jobs=${NJOBS} --compiler=${COMPILER} --disable-sandboxing \
   && eval $(opam env) \
   && opam repository add --all-switches --set-default coq-released https://coq.inria.fr/opam/released \
@@ -80,10 +83,14 @@ RUN ["/bin/bash", "--login", "-c", "set -x \
   && opam pin add -n -k version num ${NUM_VERSION} \
   && opam install -y -v -j ${NJOBS} ocamlfind dune num \
   && opam clean -a -c -s --logs \
-  && opam config list && opam list"]
+  && opam config list && opam list
 
 ENTRYPOINT ["opam", "exec", "--"]
 
 CMD ["/bin/bash", "--login"]
 
 LABEL maintainer="erik@martin-dorel.org"
+
+# Restore default shell to fully preserve backward compatibility
+SHELL ["/bin/sh", "-c"]
+# Still, we may remove this line later on.
